# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
os:
  - linux
  - osx
r:
  - oldrel
  - release
  - devel
matrix:
  exclude:
  - r: oldrel
    os: osx
  - r: devel
    os: osx
notifications:
  email:
    on_success: change
    on_failure: change
addons:
  apt:
    packages:
    - libmagic-dev
r_packages:
  - testthat
before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install libmagic; fi